FROM openjdk:8-jdk-alpine

RUN apk add --no-cache openssl

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

CMD dockerize -wait tcp://app_mysql:3306 -timeout 30s

ENTRYPOINT ["java","-jar","/app.jar"]
