FROM openjdk:8-jdk-alpine

RUN addgroup -S spring && adduser -S spring -G spring

USER spring:spring

ARG DEPENDENCY=target/dependency

COPY ${DEPENDENCY}/BOOT-INF/lib /app/backend/lib

COPY ${DEPENDENCY}/META-INF /app/backend/META-INF

COPY ${DEPENDENCY}/BOOT-INF/classes /app/backend

ENTRYPOINT ["java","-cp","app:app/backend/lib/*","hello.Application"]